project_name: minter-sentinel

builds:
  - goos:
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    files:
      - config.example.yaml

dockers:
  - goos: linux
    goarch: amd64

    ids: ["minter-sentinel"]

    image_templates:
      - "friendstrust/minter-sentinel:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "friendstrust/minter-sentinel:{{ .Major }}.{{ .Minor }}"
      - "friendstrust/minter-sentinel:{{ .Major }}"
      - "friendstrust/minter-sentinel:latest"

    dockerfile: Dockerfile

    extra_files:
      - cmd
      - config
      - services
      - go.mod
      - go.sum
      - main.go

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"