telegram:
  # Leave empty if you don't want to receive Telegram notifications
  token: ''
  admins:
    # You can get your ID from @myidbot
    # - 12345

minter:
  testnet: true
  node_api:
    - https://node-api.testnet.minter.network/v2
  # Public key of validator
  public_key: ""
  # Transaction to turn off masternode. Use txgenerate command to generate one
  transaction_off: ""
  # Missed blocks threshold before masternode will go off
  missed_blocks_threshold: 4
  # Number of seconds to sleep between checking for missed blocks
  sleep: 1
  # Removed missed block after the defined amount of signed blocks
  missed_block_remove_after: 24

prometheus:
  enabled: false
  address: :2112
